# Generated by Django 5.1.2 on 2024-12-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedusertask',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prousertask',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unloggedusertask',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
