# Generated by Django 5.1.2 on 2024-12-15 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prousertask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='welcome.project'),
        ),
    ]
