# Generated by Django 5.1.2 on 2024-12-28 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0010_memberprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='role',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='uploaded_icons/')),
                ('employee_file', models.FileField(upload_to='employee_files/')),
                ('members', models.ManyToManyField(related_name='member_of_businesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
